[zookeeper]
servers=[ "docker.for.mac.localhost:2181" ]
timeout=6
root-path="/burrow"

[cluster.local]
class-name="kafka"
servers=[ "docker.for.mac.localhost:9092", "docker.for.mac.localhost:9093","docker.for.mac.localhost:9094" ]
topic-refresh=10
offset-refresh=10

[consumer.local]
class-name="kafka"
cluster="local"
servers=[ "docker.for.mac.localhost:9092", "docker.for.mac.localhost:9093","docker.for.mac.localhost:9094" ]
group-denylist="^(console-consumer-|python-kafka-consumer-).*$"
group-allowlist=""

[consumer.local_zk]
class-name="kafka_zk"
cluster="local"
servers=[ "docker.for.mac.localhost:2181" ]
zookeeper-path="/local"
zookeeper-timeout=30
group-denylist="^(console-consumer-|python-kafka-consumer-).*$"
group-allowlist=""

[httpserver.default]
address=":8000"
